package Timer;


/**
* Timer/DateTimeServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DateTimeServer.idl
* sábado 21 de abril de 2018 14H58' CDT
*/

public interface DateTimeServerOperations  extends Timer.TimeServerOperations
{
  Timer.DateTimeServerPackage.DateTime get_date_time ();
} // interface DateTimeServerOperations
