package Timer;


/**
* Timer/DateTimeServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DateTimeServer.idl
* sábado 21 de abril de 2018 14H58' CDT
*/

public interface DateTimeServer extends DateTimeServerOperations, Timer.TimeServer, org.omg.CORBA.portable.IDLEntity 
{
} // interface DateTimeServer
