package Timer;


/**
* Timer/TimeServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DateTimeServer.idl
* sábado 21 de abril de 2018 14H58' CDT
*/

public interface TimeServerOperations 
{
  Timer.TimeServerPackage.Time get_time ();
} // interface TimeServerOperations
