package CFactory.CounterFactoryPackage;

/**
* CFactory/CounterFactoryPackage/KindHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CounterFactory.idl
* lunes 16 de abril de 2018 15H34' CDT
*/

public final class KindHolder implements org.omg.CORBA.portable.Streamable
{
  public CFactory.CounterFactoryPackage.Kind value = null;

  public KindHolder ()
  {
  }

  public KindHolder (CFactory.CounterFactoryPackage.Kind initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CFactory.CounterFactoryPackage.KindHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CFactory.CounterFactoryPackage.KindHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CFactory.CounterFactoryPackage.KindHelper.type ();
  }

}
