package CFactory.CounterFactoryPackage;


/**
* CFactory/CounterFactoryPackage/Kind.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CounterFactory.idl
* lunes 16 de abril de 2018 15H34' CDT
*/

public class Kind implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 2;
  private static CFactory.CounterFactoryPackage.Kind[] __array = new CFactory.CounterFactoryPackage.Kind [__size];

  public static final int _SHARED = 0;
  public static final CFactory.CounterFactoryPackage.Kind SHARED = new CFactory.CounterFactoryPackage.Kind(_SHARED);
  public static final int _UNSHARED = 1;
  public static final CFactory.CounterFactoryPackage.Kind UNSHARED = new CFactory.CounterFactoryPackage.Kind(_UNSHARED);

  public int value ()
  {
    return __value;
  }

  public static CFactory.CounterFactoryPackage.Kind from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected Kind (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class Kind
