package CFactory.CounterFactoryPackage;


/**
* CFactory/CounterFactoryPackage/KindHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CounterFactory.idl
* lunes 16 de abril de 2018 15H34' CDT
*/

abstract public class KindHelper
{
  private static String  _id = "IDL:CFactory/CounterFactory/Kind:1.0";

  public static void insert (org.omg.CORBA.Any a, CFactory.CounterFactoryPackage.Kind that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CFactory.CounterFactoryPackage.Kind extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (CFactory.CounterFactoryPackage.KindHelper.id (), "Kind", new String[] { "SHARED", "UNSHARED"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CFactory.CounterFactoryPackage.Kind read (org.omg.CORBA.portable.InputStream istream)
  {
    return CFactory.CounterFactoryPackage.Kind.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CFactory.CounterFactoryPackage.Kind value)
  {
    ostream.write_long (value.value ());
  }

}
