package Count;

/**
* Count/CounterHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CounterFactory.idl
* lunes 16 de abril de 2018 15H34' CDT
*/

public final class CounterHolder implements org.omg.CORBA.portable.Streamable
{
  public Count.Counter value = null;

  public CounterHolder ()
  {
  }

  public CounterHolder (Count.Counter initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Count.CounterHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Count.CounterHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Count.CounterHelper.type ();
  }

}
