package CFactory;


/**
* CFactory/CounterFactoryHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CounterFactory.idl
* lunes 16 de abril de 2018 15H34' CDT
*/

abstract public class CounterFactoryHelper
{
  private static String  _id = "IDL:CFactory/CounterFactory:1.0";

  public static void insert (org.omg.CORBA.Any a, CFactory.CounterFactory that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CFactory.CounterFactory extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (CFactory.CounterFactoryHelper.id (), "CounterFactory");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CFactory.CounterFactory read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CounterFactoryStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CFactory.CounterFactory value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static CFactory.CounterFactory narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CFactory.CounterFactory)
      return (CFactory.CounterFactory)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CFactory._CounterFactoryStub stub = new CFactory._CounterFactoryStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static CFactory.CounterFactory unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CFactory.CounterFactory)
      return (CFactory.CounterFactory)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CFactory._CounterFactoryStub stub = new CFactory._CounterFactoryStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
