package CFactory;


/**
* CFactory/CounterFactory.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CounterFactory.idl
* lunes 16 de abril de 2018 15H34' CDT
*/

public interface CounterFactory extends CounterFactoryOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CounterFactory
