package CFactory;


/**
* CFactory/CounterFactoryOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CounterFactory.idl
* lunes 16 de abril de 2018 15H34' CDT
*/

public interface CounterFactoryOperations 
{
  Count.Counter create (CFactory.CounterFactoryPackage.Kind k);
  void destroy (Count.Counter c);
} // interface CounterFactoryOperations
