package CFactory;

/**
* CFactory/CounterFactoryHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CounterFactory.idl
* lunes 16 de abril de 2018 15H34' CDT
*/

public final class CounterFactoryHolder implements org.omg.CORBA.portable.Streamable
{
  public CFactory.CounterFactory value = null;

  public CounterFactoryHolder ()
  {
  }

  public CounterFactoryHolder (CFactory.CounterFactory initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CFactory.CounterFactoryHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CFactory.CounterFactoryHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CFactory.CounterFactoryHelper.type ();
  }

}
