package CFactory;


/**
* CFactory/CounterFactoryPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CounterFactory.idl
* lunes 16 de abril de 2018 15H34' CDT
*/

public abstract class CounterFactoryPOA extends org.omg.PortableServer.Servant
 implements CFactory.CounterFactoryOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("create", new java.lang.Integer (0));
    _methods.put ("destroy", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // CFactory/CounterFactory/create
       {
         CFactory.CounterFactoryPackage.Kind k = CFactory.CounterFactoryPackage.KindHelper.read (in);
         Count.Counter $result = null;
         $result = this.create (k);
         out = $rh.createReply();
         Count.CounterHelper.write (out, $result);
         break;
       }

       case 1:  // CFactory/CounterFactory/destroy
       {
         Count.Counter c = Count.CounterHelper.read (in);
         this.destroy (c);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CFactory/CounterFactory:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public CounterFactory _this() 
  {
    return CounterFactoryHelper.narrow(
    super._this_object());
  }

  public CounterFactory _this(org.omg.CORBA.ORB orb) 
  {
    return CounterFactoryHelper.narrow(
    super._this_object(orb));
  }


} // class CounterFactoryPOA
