package HolaM;


/**
* HolaM/HolaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hola.idl
* viernes 16 de marzo de 2018 12H03' CST
*/

public interface HolaOperations 
{
  String diHola ();
  void shutdown ();
} // interface HolaOperations
