package HolaM;

/**
* HolaM/HolaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hola.idl
* viernes 16 de marzo de 2018 12H03' CST
*/

public final class HolaHolder implements org.omg.CORBA.portable.Streamable
{
  public HolaM.Hola value = null;

  public HolaHolder ()
  {
  }

  public HolaHolder (HolaM.Hola initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HolaM.HolaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HolaM.HolaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HolaM.HolaHelper.type ();
  }

}
