package HolaM;


/**
* HolaM/HolaPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hola.idl
* viernes 16 de marzo de 2018 12H03' CST
*/

public abstract class HolaPOA extends org.omg.PortableServer.Servant
 implements HolaM.HolaOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("diHola", new java.lang.Integer (0));
    _methods.put ("shutdown", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // HolaM/Hola/diHola
       {
         String $result = null;
         $result = this.diHola ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // HolaM/Hola/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:HolaM/Hola:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Hola _this() 
  {
    return HolaHelper.narrow(
    super._this_object());
  }

  public Hola _this(org.omg.CORBA.ORB orb) 
  {
    return HolaHelper.narrow(
    super._this_object(orb));
  }


} // class HolaPOA
