package HolaM;


/**
* HolaM/Hola.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hola.idl
* viernes 16 de marzo de 2018 12H03' CST
*/

public interface Hola extends HolaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hola
