package CBCount;


/**
* CBCount/CounterClient.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CBCounter.idl
* lunes 23 de abril de 2018 08H41' CDT
*/

public interface CounterClient extends CounterClientOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CounterClient
