package CBCount;

/**
* CBCount/CounterHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CBCounter.idl
* lunes 23 de abril de 2018 08H41' CDT
*/

public final class CounterHolder implements org.omg.CORBA.portable.Streamable
{
  public CBCount.Counter value = null;

  public CounterHolder ()
  {
  }

  public CounterHolder (CBCount.Counter initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CBCount.CounterHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CBCount.CounterHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CBCount.CounterHelper.type ();
  }

}
