package CBCount;


/**
* CBCount/CounterClientOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CBCounter.idl
* lunes 23 de abril de 2018 08H41' CDT
*/

public interface CounterClientOperations 
{
  void update (int value);
} // interface CounterClientOperations
