package CBCount;


/**
* CBCount/CounterOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CBCounter.idl
* lunes 23 de abril de 2018 08H41' CDT
*/

public interface CounterOperations 
{
  int value ();
  void inc ();
  void dec ();
  void add (CBCount.CounterClient cc);
  void remove (CBCount.CounterClient cc);
} // interface CounterOperations
