package CalcO;


/**
* CalcO/Operation.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CalcO.idl
* jueves 29 de marzo de 2018 01H50' CST
*/

public final class Operation implements org.omg.CORBA.portable.IDLEntity
{
  public double a = (double)0;
  public double b = (double)0;

  public Operation ()
  {
  } // ctor

  public Operation (double _a, double _b)
  {
    a = _a;
    b = _b;
  } // ctor

    public Operation (double _a)
  {
    a = _a;
  } // ctor

    public double getA() {
        return a;
    }

} // class Operation
