package CalcO;


/**
* CalcO/Ops.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CalcO.idl
* miércoles 28 de marzo de 2018 19H12' CST
*/

public interface Ops extends OpsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Ops
