package CalcO;

/**
* CalcO/OpsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CalcO.idl
* jueves 29 de marzo de 2018 01H50' CST
*/

public final class OpsHolder implements org.omg.CORBA.portable.Streamable
{
  public CalcO.Ops value = null;

  public OpsHolder ()
  {
  }

  public OpsHolder (CalcO.Ops initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CalcO.OpsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CalcO.OpsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CalcO.OpsHelper.type ();
  }

}
