package CalcO;


/**
* CalcO/OpsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CalcO.idl
* miércoles 28 de marzo de 2018 19H12' CST
*/

public interface OpsOperations 
{
  double add (CalcO.Operation op);
  double sust (CalcO.Operation op);
  double mult (CalcO.Operation op);
  double div (CalcO.Operation op);
  double fact (CalcO.Operation op);
} // interface OpsOperations
