package Count;


/**
* Count/CounterOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CounterFactory.idl
* lunes 16 de abril de 2018 15H34' CDT
*/

public interface CounterOperations 
{
  int value ();
  void inc ();
  void dec ();
} // interface CounterOperations
