package Timer;


/**
* Timer/TimeServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Timer.idl
* sábado 21 de abril de 2018 14H34' CDT
*/

public interface TimeServer extends TimeServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface TimeServer
