package Timer;


/**
* Timer/TimeServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Timer.idl
* sábado 21 de abril de 2018 14H34' CDT
*/

public interface TimeServerOperations 
{
  int hours ();
  int minutes ();
  int seconds ();
} // interface TimeServerOperations
