package XYZ;


/**
* XYZ/X.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from XYZ.idl
* sábado 21 de abril de 2018 15H15' CDT
*/

public interface X extends XOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface X
