package XYZ;

/**
* XYZ/XHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from XYZ.idl
* sábado 21 de abril de 2018 15H15' CDT
*/

public final class XHolder implements org.omg.CORBA.portable.Streamable
{
  public XYZ.X value = null;

  public XHolder ()
  {
  }

  public XHolder (XYZ.X initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = XYZ.XHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    XYZ.XHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return XYZ.XHelper.type ();
  }

}
