package XYZ;


/**
* XYZ/Y.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from XYZ.idl
* sábado 21 de abril de 2018 15H15' CDT
*/

public interface Y extends YOperations, XYZ.X, org.omg.CORBA.portable.IDLEntity 
{
} // interface Y
