package XYZ;


/**
* XYZ/ZHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from XYZ.idl
* sábado 21 de abril de 2018 15H15' CDT
*/

abstract public class ZHelper
{
  private static String  _id = "IDL:XYZ/Z:1.0";

  public static void insert (org.omg.CORBA.Any a, XYZ.Z that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static XYZ.Z extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (XYZ.ZHelper.id (), "Z");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static XYZ.Z read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ZStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, XYZ.Z value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static XYZ.Z narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof XYZ.Z)
      return (XYZ.Z)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      XYZ._ZStub stub = new XYZ._ZStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static XYZ.Z unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof XYZ.Z)
      return (XYZ.Z)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      XYZ._ZStub stub = new XYZ._ZStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
