package XYZ;

/**
* XYZ/ZHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from XYZ.idl
* sábado 21 de abril de 2018 15H15' CDT
*/

public final class ZHolder implements org.omg.CORBA.portable.Streamable
{
  public XYZ.Z value = null;

  public ZHolder ()
  {
  }

  public ZHolder (XYZ.Z initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = XYZ.ZHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    XYZ.ZHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return XYZ.ZHelper.type ();
  }

}
