package XYZ;


/**
* XYZ/ZOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from XYZ.idl
* sábado 21 de abril de 2018 15H15' CDT
*/

public interface ZOperations  extends XYZ.YOperations
{
} // interface ZOperations
