package PublishSubscribe;

/**
* PublishSubscribe/FilterHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Filtering.idl
* martes 1 de mayo de 2018 16H02' CDT
*/

public final class FilterHolder implements org.omg.CORBA.portable.Streamable
{
  public PublishSubscribe.Filter value = null;

  public FilterHolder ()
  {
  }

  public FilterHolder (PublishSubscribe.Filter initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PublishSubscribe.FilterHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PublishSubscribe.FilterHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PublishSubscribe.FilterHelper.type ();
  }

}
