package PublishSubscribe;


/**
* PublishSubscribe/FilterHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Filtering.idl
* martes 1 de mayo de 2018 16H02' CDT
*/

abstract public class FilterHelper
{
  private static String  _id = "IDL:PublishSubscribe/Filter:1.0";


  public static void insert (org.omg.CORBA.Any a, PublishSubscribe.Filter that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static PublishSubscribe.Filter extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.ValueMember[] _members0 = new org.omg.CORBA.ValueMember[3];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          // ValueMember instance for sub
          _tcOf_members0 = PublishSubscribe.SubscriberHelper.type ();
          _members0[0] = new org.omg.CORBA.ValueMember ("sub", 
              PublishSubscribe.SubscriberHelper.id (), 
              _id, 
              "1.0", 
              _tcOf_members0, 
              null, 
              org.omg.CORBA.PRIVATE_MEMBER.value);
          // ValueMember instance for min
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_ulong);
          _members0[1] = new org.omg.CORBA.ValueMember ("min", 
              "", 
              _id, 
              "", 
              _tcOf_members0, 
              null, 
              org.omg.CORBA.PRIVATE_MEMBER.value);
          // ValueMember instance for max
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_ulong);
          _members0[2] = new org.omg.CORBA.ValueMember ("max", 
              "", 
              _id, 
              "", 
              _tcOf_members0, 
              null, 
              org.omg.CORBA.PRIVATE_MEMBER.value);
          __typeCode = org.omg.CORBA.ORB.init ().create_value_tc (_id, "Filter", org.omg.CORBA.VM_NONE.value, null, _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static PublishSubscribe.Filter read (org.omg.CORBA.portable.InputStream istream)
  {
    return (PublishSubscribe.Filter)((org.omg.CORBA_2_3.portable.InputStream) istream).read_value (id ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, PublishSubscribe.Filter value)
  {
    ((org.omg.CORBA_2_3.portable.OutputStream) ostream).write_value (value, id ());
  }


  public static PublishSubscribe.Filter init (org.omg.CORBA.ORB $orb, PublishSubscribe.Subscriber s, int min, int max)
  {
    try {
      PublishSubscribe.FilterValueFactory $factory = (PublishSubscribe.FilterValueFactory)
          ((org.omg.CORBA_2_3.ORB) $orb).lookup_value_factory(id());
      return $factory.init (s, min, max);
    } catch (ClassCastException $ex) {
      throw new org.omg.CORBA.BAD_PARAM ();
    }
  }

}
