package PublishSubscribe;

/**
* PublishSubscribe/PublisherHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Filtering.idl
* martes 1 de mayo de 2018 16H02' CDT
*/

public final class PublisherHolder implements org.omg.CORBA.portable.Streamable
{
  public PublishSubscribe.Publisher value = null;

  public PublisherHolder ()
  {
  }

  public PublisherHolder (PublishSubscribe.Publisher initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PublishSubscribe.PublisherHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PublishSubscribe.PublisherHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PublishSubscribe.PublisherHelper.type ();
  }

}
