package PublishSubscribe;


/**
* PublishSubscribe/PublisherPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Filtering.idl
* martes 1 de mayo de 2018 16H02' CDT
*/

public abstract class PublisherPOA extends org.omg.PortableServer.Servant
 implements PublishSubscribe.PublisherOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("add", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // PublishSubscribe/Publisher/add
       {
         PublishSubscribe.Filter f = PublishSubscribe.FilterHelper.read (in);
         this.add (f);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:PublishSubscribe/Publisher:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Publisher _this() 
  {
    return PublisherHelper.narrow(
    super._this_object());
  }

  public Publisher _this(org.omg.CORBA.ORB orb) 
  {
    return PublisherHelper.narrow(
    super._this_object(orb));
  }


} // class PublisherPOA
