package PublishSubscribe;


/**
* PublishSubscribe/PublisherOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Filtering.idl
* martes 1 de mayo de 2018 16H02' CDT
*/

public interface PublisherOperations 
{
  void add (PublishSubscribe.Filter f);
} // interface PublisherOperations
