package PublishSubscribe;


/**
* PublishSubscribe/SubscriberOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Filtering.idl
* martes 1 de mayo de 2018 16H02' CDT
*/

public interface SubscriberOperations 
{
  void _notify (int value);
} // interface SubscriberOperations
