package PublishSubscribe;

/**
* PublishSubscribe/SubscriberHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Filtering.idl
* martes 1 de mayo de 2018 16H02' CDT
*/

public final class SubscriberHolder implements org.omg.CORBA.portable.Streamable
{
  public PublishSubscribe.Subscriber value = null;

  public SubscriberHolder ()
  {
  }

  public SubscriberHolder (PublishSubscribe.Subscriber initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PublishSubscribe.SubscriberHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PublishSubscribe.SubscriberHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PublishSubscribe.SubscriberHelper.type ();
  }

}
