package PublishSubscribe;


/**
* PublishSubscribe/Subscriber.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Filtering.idl
* martes 1 de mayo de 2018 16H02' CDT
*/

public interface Subscriber extends SubscriberOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Subscriber
