package AuctionSist;


/**
* AuctionSist/AuctionHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from auction.idl
* miércoles 30 de mayo de 2018 05H11' CDT
*/

abstract public class AuctionHelper
{
  private static String  _id = "IDL:AuctionSist/Auction:1.0";

  public static void insert (org.omg.CORBA.Any a, AuctionSist.Auction that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static AuctionSist.Auction extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (AuctionSist.AuctionHelper.id (), "Auction");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static AuctionSist.Auction read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_AuctionStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, AuctionSist.Auction value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static AuctionSist.Auction narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof AuctionSist.Auction)
      return (AuctionSist.Auction)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      AuctionSist._AuctionStub stub = new AuctionSist._AuctionStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static AuctionSist.Auction unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof AuctionSist.Auction)
      return (AuctionSist.Auction)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      AuctionSist._AuctionStub stub = new AuctionSist._AuctionStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
