package AuctionSist;


/**
* AuctionSist/AuctionClientOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from auction.idl
* miércoles 30 de mayo de 2018 05H11' CDT
*/

public interface AuctionClientOperations 
{
  void update (int value);
  void quit ();
} // interface AuctionClientOperations
