package AuctionSist;

/**
* AuctionSist/AuctionClientHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from auction.idl
* miércoles 30 de mayo de 2018 05H11' CDT
*/

public final class AuctionClientHolder implements org.omg.CORBA.portable.Streamable
{
  public AuctionSist.AuctionClient value = null;

  public AuctionClientHolder ()
  {
  }

  public AuctionClientHolder (AuctionSist.AuctionClient initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AuctionSist.AuctionClientHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AuctionSist.AuctionClientHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AuctionSist.AuctionClientHelper.type ();
  }

}
