package AuctionSist;


/**
* AuctionSist/AuctionClientPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from auction.idl
* miércoles 30 de mayo de 2018 05H11' CDT
*/

public abstract class AuctionClientPOA extends org.omg.PortableServer.Servant
 implements AuctionSist.AuctionClientOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("update", new java.lang.Integer (0));
    _methods.put ("quit", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // AuctionSist/AuctionClient/update
       {
         int value = in.read_long ();
         this.update (value);
         out = $rh.createReply();
         break;
       }

       case 1:  // AuctionSist/AuctionClient/quit
       {
         this.quit ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:AuctionSist/AuctionClient:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public AuctionClient _this() 
  {
    return AuctionClientHelper.narrow(
    super._this_object());
  }

  public AuctionClient _this(org.omg.CORBA.ORB orb) 
  {
    return AuctionClientHelper.narrow(
    super._this_object(orb));
  }


} // class AuctionClientPOA
