package AuctionSist;


/**
* AuctionSist/Auction.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from auction.idl
* miércoles 30 de mayo de 2018 05H11' CDT
*/

public interface Auction extends AuctionOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Auction
