package AuctionSist;

/**
* AuctionSist/AuctionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from auction.idl
* miércoles 30 de mayo de 2018 05H11' CDT
*/

public final class AuctionHolder implements org.omg.CORBA.portable.Streamable
{
  public AuctionSist.Auction value = null;

  public AuctionHolder ()
  {
  }

  public AuctionHolder (AuctionSist.Auction initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AuctionSist.AuctionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AuctionSist.AuctionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AuctionSist.AuctionHelper.type ();
  }

}
