package AuctionSist;


/**
* AuctionSist/AuctionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from auction.idl
* miércoles 30 de mayo de 2018 05H11' CDT
*/

public interface AuctionOperations 
{
  double originalPrice ();
  double finalPrice ();
  String name ();
  String client ();
  void bid ();
  void add (AuctionSist.AuctionClient cc);
  void remove (AuctionSist.AuctionClient cc);
} // interface AuctionOperations
