/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clientechido;

import javax.swing.JTextField;

/**
 *
 * @author HP
 */
public class PanelChido extends javax.swing.JPanel {
Cliente cliente =new Cliente();
    
    /**
     * Creates new form PanelChido
     */
    public PanelChido() {
        initComponents();
        this.etiquetaR.setText(cliente.countREST()+" records on database");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelNorte = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        campoB = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campoRR = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoR = new javax.swing.JTextField();
        botonBuscar = new javax.swing.JButton();
        campoCentro = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        campoID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        campoArt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        campoName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        campoYear = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        campoGenre = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        campoTrack = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        botonAdd = new javax.swing.JButton();
        botonUpdate = new javax.swing.JButton();
        botonDelete = new javax.swing.JButton();
        botonClr = new javax.swing.JButton();
        etiquetaR = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Buscar");
        panelNorte.add(jLabel1);

        campoB.setColumns(3);
        campoB.setName("sid"); // NOI18N
        campoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoBActionPerformed(evt);
            }
        });
        panelNorte.add(campoB);

        jLabel2.setText("De");
        panelNorte.add(jLabel2);

        campoRR.setColumns(3);
        campoRR.setName("ri"); // NOI18N
        panelNorte.add(campoRR);

        jLabel3.setText("hasta");
        panelNorte.add(jLabel3);

        campoR.setColumns(3);
        campoR.setName("rf"); // NOI18N
        panelNorte.add(campoR);

        botonBuscar.setText("Search");
        botonBuscar.setName("search"); // NOI18N
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });
        panelNorte.add(botonBuscar);

        jPanel1.add(panelNorte, java.awt.BorderLayout.NORTH);

        campoCentro.setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 10));
        campoCentro.setLayout(new java.awt.GridLayout(3, 2, 10, 15));

        jLabel4.setText("id");
        campoCentro.add(jLabel4);

        campoID.setColumns(20);
        campoCentro.add(campoID);

        jLabel5.setText("artist");
        campoCentro.add(jLabel5);

        campoArt.setColumns(20);
        campoCentro.add(campoArt);

        jLabel6.setText("name");
        campoCentro.add(jLabel6);

        campoName.setColumns(20);
        campoCentro.add(campoName);

        jLabel7.setText("year");
        campoCentro.add(jLabel7);

        campoYear.setColumns(20);
        campoCentro.add(campoYear);

        jLabel8.setText("genre");
        campoCentro.add(jLabel8);

        campoGenre.setColumns(20);
        campoCentro.add(campoGenre);

        jLabel9.setText("number of tracks");
        campoCentro.add(jLabel9);

        campoTrack.setColumns(20);
        campoCentro.add(campoTrack);

        jPanel1.add(campoCentro, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        botonAdd.setText("Add");
        botonAdd.setName("add"); // NOI18N
        botonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAddActionPerformed(evt);
            }
        });
        jPanel2.add(botonAdd);

        botonUpdate.setText("Update");
        botonUpdate.setName("act"); // NOI18N
        botonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(botonUpdate);

        botonDelete.setText("Delete");
        botonDelete.setName("del"); // NOI18N
        botonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(botonDelete);

        botonClr.setText("Clear");
        botonClr.setName("clr"); // NOI18N
        jPanel2.add(botonClr);

        etiquetaR.setText("   records");
        jPanel2.add(etiquetaR);

        add(jPanel2, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void botonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAddActionPerformed

    private void botonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonUpdateActionPerformed

    private void botonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonDeleteActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void campoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAdd;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonClr;
    private javax.swing.JButton botonDelete;
    private javax.swing.JButton botonUpdate;
    private javax.swing.JTextField campoArt;
    private javax.swing.JTextField campoB;
    private javax.swing.JPanel campoCentro;
    private javax.swing.JTextField campoGenre;
    private javax.swing.JTextField campoID;
    private javax.swing.JTextField campoName;
    private javax.swing.JTextField campoR;
    private javax.swing.JTextField campoRR;
    private javax.swing.JTextField campoTrack;
    private javax.swing.JTextField campoYear;
    private javax.swing.JLabel etiquetaR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelNorte;
    // End of variables declaration//GEN-END:variables

    void addEventos(OyenteChido o) {
   this.campoB.addActionListener(o); //campo enter
   this.botonAdd.addActionListener(o);
   this.botonBuscar.addActionListener(o);
   this.botonUpdate.addActionListener(o);
   this.botonDelete.addActionListener(o);
   this.botonClr.addActionListener(o);
    }

    public javax.swing.JButton getBotonAdd() {
        return botonAdd;
    }

    public void setBotonAdd(javax.swing.JButton botonAdd) {
        this.botonAdd = botonAdd;
    }

    public javax.swing.JButton getBotonBuscar() {
        return botonBuscar;
    }

    public void setBotonBuscar(javax.swing.JButton botonBuscar) {
        this.botonBuscar = botonBuscar;
    }

    public javax.swing.JButton getBotonDelete() {
        return botonDelete;
    }

    public void setBotonDelete(javax.swing.JButton botonDelete) {
        this.botonDelete = botonDelete;
    }

    public javax.swing.JButton getBotonUpdate() {
        return botonUpdate;
    }

    public void setBotonUpdate(javax.swing.JButton botonUpdate) {
        this.botonUpdate = botonUpdate;
    }

    public javax.swing.JTextField getCampoB() {
        return campoB;
    }

    public void setCampoB(javax.swing.JTextField campoB) {
        this.campoB = campoB;
    }

    public javax.swing.JPanel getCampoCentro() {
        return campoCentro;
    }

    public void setCampoCentro(javax.swing.JPanel campoCentro) {
        this.campoCentro = campoCentro;
    }

    public javax.swing.JTextField getCampoR() {
        return campoR;
    }

    public void setCampoR(javax.swing.JTextField campoR) {
        this.campoR = campoR;
    }

    public javax.swing.JTextField getCampoRR() {
        return campoRR;
    }

    public void setCampoRR(javax.swing.JTextField campoRR) {
        this.campoRR = campoRR;
    }

    public javax.swing.JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(javax.swing.JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public javax.swing.JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(javax.swing.JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public javax.swing.JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(javax.swing.JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public javax.swing.JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(javax.swing.JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public javax.swing.JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(javax.swing.JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public javax.swing.JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(javax.swing.JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public javax.swing.JLabel getjLabel7() {
        return jLabel7;
    }

    public void setjLabel7(javax.swing.JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    public javax.swing.JLabel getjLabel8() {
        return jLabel8;
    }

    public void setjLabel8(javax.swing.JLabel jLabel8) {
        this.jLabel8 = jLabel8;
    }

    public javax.swing.JLabel getjLabel9() {
        return jLabel9;
    }

    public void setjLabel9(javax.swing.JLabel jLabel9) {
        this.jLabel9 = jLabel9;
    }

    public javax.swing.JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(javax.swing.JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public javax.swing.JPanel getjPanel2() {
        return jPanel2;
    }

    public JTextField getCampoArt() {
        return campoArt;
    }

    public void setCampoArt(JTextField campoArt) {
        this.campoArt = campoArt;
    }

    public JTextField getCampoGenre() {
        return campoGenre;
    }

    public void setCampoGenre(JTextField campoGenre) {
        this.campoGenre = campoGenre;
    }

    public JTextField getCampoID() {
        return campoID;
    }

    public void setCampoID(JTextField campoID) {
        this.campoID = campoID;
    }

    public JTextField getCampoName() {
        return campoName;
    }

    public void setCampoName(JTextField campoName) {
        this.campoName = campoName;
    }

    public JTextField getCampoTrack() {
        return campoTrack;
    }

    public void setCampoTrack(JTextField campoTrack) {
        this.campoTrack = campoTrack;
    }

    public JTextField getCampoYear() {
        return campoYear;
    }

    public void setCampoYear(JTextField campoYear) {
        this.campoYear = campoYear;
    }

    public void setjPanel2(javax.swing.JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public javax.swing.JTextField getjTextField1() {
        return campoID;
    }

    public void setjTextField1(javax.swing.JTextField jTextField1) {
        this.campoID = jTextField1;
    }

    public javax.swing.JTextField getjTextField2() {
        return campoArt;
    }

    public void setjTextField2(javax.swing.JTextField jTextField2) {
        this.campoArt = jTextField2;
    }

    public javax.swing.JTextField getjTextField3() {
        return campoName;
    }

    public void setjTextField3(javax.swing.JTextField jTextField3) {
        this.campoName = jTextField3;
    }

    public javax.swing.JTextField getjTextField4() {
        return campoYear;
    }

    public void setjTextField4(javax.swing.JTextField jTextField4) {
        this.campoYear = jTextField4;
    }

    public javax.swing.JTextField getjTextField5() {
        return campoGenre;
    }

    public void setjTextField5(javax.swing.JTextField jTextField5) {
        this.campoGenre = jTextField5;
    }

    public javax.swing.JTextField getjTextField6() {
        return campoTrack;
    }

    public void setjTextField6(javax.swing.JTextField jTextField6) {
        this.campoTrack = jTextField6;
    }

    public javax.swing.JPanel getPanelNorte() {
        return panelNorte;
    }

    public void setPanelNorte(javax.swing.JPanel panelNorte) {
        this.panelNorte = panelNorte;
    }
}
