
// CBCounter.idl
module AuctionSist
{
interface AuctionClient
{
void update(in long value);
void quit();

};

interface Auction
{
readonly attribute double originalPrice;
readonly attribute double finalPrice;
readonly attribute string name;
readonly attribute string client;
string setName(in string name);
string setClient(in string client);
void bid(in long value);
void add(in AuctionClient cc);
void remove(in AuctionClient cc);
};
};