    /**
     *
     * @author imed & Arana De Dorós
     */
    module CalcApp
    {
      interface Calculator
      {
        long add(in long a,in long b);
        long sust(in long a, in long b);
        long mult(in long a, in long b);
        long div(in long a, in long b);
        oneway void shutdown();};
    };
