    /**
     *
     * @author imed & Arana De Dorós
     */
    module CalcApp
    {
      interface Calculator
      {
        double add(in float a,in float b);
        double sust(in float a, in float b);
        double mult(in float a, in float b);
        double div(in float a, in float b);
        double fact(in float a);
        
        oneway void shutdown();};
    };  
