
/**
* Counter.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Counter.idl
* jueves 12 de abril de 2018 08H47' CDT
*/


// Counter.idl
public interface Counter extends CounterOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Counter
