
/**
* CounterOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Counter.idl
* jueves 12 de abril de 2018 08H47' CDT
*/


// Counter.idl
public interface CounterOperations 
{
  int value ();
  void inc ();
  void dec ();
} // interface CounterOperations
