package Timer;


/**
* Timer/TimeServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TimeServer.idl
* viernes 20 de abril de 2018 23H57' CDT
*/

public interface TimeServerOperations 
{
  int hours ();
  int minutes ();
  int seconds ();
} // interface TimeServerOperations
