package AuctionSist;


/**
* AuctionSist/AuctionClientOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from auction.idl
* viernes 1 de junio de 2018 17H40' CDT
*/

public interface AuctionClientOperations 
{
  void update (int value);
  void quit ();
} // interface AuctionClientOperations
