package AuctionSist;


/**
* AuctionSist/AuctionObjectHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from auction.idl
* domingo 20 de mayo de 2018 15H40' CDT
*/

abstract public class AuctionObjectHelper
{
  private static String  _id = "IDL:AuctionSist/AuctionObject:1.0";

  public static void insert (org.omg.CORBA.Any a, corbaauctionsystem.AuctionObject that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static corbaauctionsystem.AuctionObject extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [4];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "client",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "name",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_double);
          _members0[2] = new org.omg.CORBA.StructMember (
            "originalPrice",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_double);
          _members0[3] = new org.omg.CORBA.StructMember (
            "finalPrice",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (AuctionSist.AuctionObjectHelper.id (), "AuctionObject", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static corbaauctionsystem.AuctionObject read (org.omg.CORBA.portable.InputStream istream)
  {
    corbaauctionsystem.AuctionObject value = new corbaauctionsystem.AuctionObject ();
    value.setClient(istream.read_string ());
    value.setName(istream.read_string ());
    value.setOriginalPrice(istream.read_double ());
    value.setFinalPrice(istream.read_double ());
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, corbaauctionsystem.AuctionObject value)
  {
    ostream.write_string (value.getClient());
    ostream.write_string (value.getName());
    ostream.write_double (value.getOriginalPrice());
    ostream.write_double (value.getFinalPrice());
  }

}
