package AuctionSist;

/**
* AuctionSist/AuctionObjectHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from auction.idl
* domingo 20 de mayo de 2018 15H40' CDT
*/

public final class AuctionObjectHolder implements org.omg.CORBA.portable.Streamable
{
  public corbaauctionsystem.AuctionObject value = null;

  public AuctionObjectHolder ()
  {
  }

  public AuctionObjectHolder (corbaauctionsystem.AuctionObject initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AuctionSist.AuctionObjectHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AuctionSist.AuctionObjectHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AuctionSist.AuctionObjectHelper.type ();
  }

}
