package AuctionSist;


/**
* AuctionSist/Auction.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from auction.idl
* viernes 1 de junio de 2018 17H40' CDT
*/

public interface Auction extends AuctionOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Auction
