package AuctionSist;

/**
* AuctionSist/AuctionOpsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from auction.idl
* domingo 20 de mayo de 2018 15H40' CDT
*/

public final class AuctionOpsHolder implements org.omg.CORBA.portable.Streamable
{
  public AuctionSist.AuctionOps value = null;

  public AuctionOpsHolder ()
  {
  }

  public AuctionOpsHolder (AuctionSist.AuctionOps initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AuctionSist.AuctionOpsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AuctionSist.AuctionOpsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AuctionSist.AuctionOpsHelper.type ();
  }

}
