package AuctionSist;


/**
* AuctionSist/AuctionOpsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from auction.idl
* domingo 20 de mayo de 2018 15H40' CDT
*/

public interface AuctionOpsOperations 
{
  corbaauctionsystem.AuctionObject bid (corbaauctionsystem.AuctionObject obj);
  void _notify (corbaauctionsystem.AuctionObject obj);
  void quit (corbaauctionsystem.AuctionObject obj);
  void shutdown ();
} // interface AuctionOpsOperations
