package AuctionSist;


/**
* AuctionSist/AuctionOps.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from auction.idl
* domingo 20 de mayo de 2018 15H40' CDT
*/

public interface AuctionOps extends AuctionOpsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AuctionOps
