package AuctionSist;


/**
* AuctionSist/AuctionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from auction.idl
* viernes 1 de junio de 2018 17H40' CDT
*/

public interface AuctionOperations 
{
  double originalPrice ();
  double finalPrice ();
  String name ();
  String client ();
  String setName (String name);
  String setClient (String client);
  void bid (int value);
  void add (AuctionSist.AuctionClient cc);
  void remove (AuctionSist.AuctionClient cc);
} // interface AuctionOperations
