package Timer;


/**
* Timer/TimeServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Timer.idl
* sábado 21 de abril de 2018 14H48' CDT
*/

public interface TimeServerOperations 
{
  void get_time (org.omg.CORBA.IntHolder hours, org.omg.CORBA.IntHolder minutes, org.omg.CORBA.IntHolder seconds);
} // interface TimeServerOperations
