package Timer;

/**
* Timer/TimeServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Timer.idl
* sábado 21 de abril de 2018 14H48' CDT
*/

public final class TimeServerHolder implements org.omg.CORBA.portable.Streamable
{
  public Timer.TimeServer value = null;

  public TimeServerHolder ()
  {
  }

  public TimeServerHolder (Timer.TimeServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Timer.TimeServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Timer.TimeServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Timer.TimeServerHelper.type ();
  }

}
