package CalcApp;

/**
* CalcApp/AdditionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calc.idl
* viernes 16 de marzo de 2018 12H55' CST
*/

public final class AdditionHolder implements org.omg.CORBA.portable.Streamable
{
  public CalcApp.Addition value = null;

  public AdditionHolder ()
  {
  }

  public AdditionHolder (CalcApp.Addition initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CalcApp.AdditionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CalcApp.AdditionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CalcApp.AdditionHelper.type ();
  }

}
