package CalcApp;


/**
* CalcApp/Addition.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calc.idl
* viernes 16 de marzo de 2018 12H55' CST
*/

public interface Addition extends AdditionOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Addition
