package CalcApp;


/**
* CalcApp/CalculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calc.idl
* sábado 17 de marzo de 2018 11H14' CST
*/

public interface CalculatorOperations 
{
  double add (float a, float b);
  double sust (float a, float b);
  double mult (float a, float b);
  double div (float a, float b);
  double fact (float a);
  void shutdown ();
} // interface CalculatorOperations
