package CalcApp;

/**
* CalcApp/CalculatorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calc.idl
* sábado 17 de marzo de 2018 11H14' CST
*/

public final class CalculatorHolder implements org.omg.CORBA.portable.Streamable
{
  public CalcApp.Calculator value = null;

  public CalculatorHolder ()
  {
  }

  public CalculatorHolder (CalcApp.Calculator initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CalcApp.CalculatorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CalcApp.CalculatorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CalcApp.CalculatorHelper.type ();
  }

}
