package CalcApp;


/**
* CalcApp/Calculator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calc.idl
* sábado 17 de marzo de 2018 11H14' CST
*/

public interface Calculator extends CalculatorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Calculator
