package CalcApp;

/**
* CalcApp/DivisionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calc.idl
* viernes 16 de marzo de 2018 12H55' CST
*/

public final class DivisionHolder implements org.omg.CORBA.portable.Streamable
{
  public CalcApp.Division value = null;

  public DivisionHolder ()
  {
  }

  public DivisionHolder (CalcApp.Division initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CalcApp.DivisionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CalcApp.DivisionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CalcApp.DivisionHelper.type ();
  }

}
