package CalcApp;


/**
* CalcApp/DivisionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calc.idl
* viernes 16 de marzo de 2018 12H55' CST
*/

public interface DivisionOperations 
{
  int div (int a, int b);
  void shutdown ();
} // interface DivisionOperations
