package CalcApp;

/**
* CalcApp/MultiplicationHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calc.idl
* viernes 16 de marzo de 2018 12H55' CST
*/

public final class MultiplicationHolder implements org.omg.CORBA.portable.Streamable
{
  public CalcApp.Multiplication value = null;

  public MultiplicationHolder ()
  {
  }

  public MultiplicationHolder (CalcApp.Multiplication initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CalcApp.MultiplicationHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CalcApp.MultiplicationHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CalcApp.MultiplicationHelper.type ();
  }

}
